"""
Task 12
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
"""


def check_factors(i):
    count = 0
    for j in range(1, int(i ** 0.5) + 1):
        if i % j == 0:
            count += 2 #To account for both divisors
    if int(i ** 0.5) + 1 == i:
        count -= 1 #Prevent recount
    return count


def main():
    n = 1
    while True:
        tn = int(n * (n + 1) / 2)  # Formula for triangle number
        factors = check_factors(tn)
        print(tn, factors, n)
        if factors >= 500:
            print(tn, n)
            break
        n += 1


main()
