"""
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

final_sum = 0
current = 1
prev = 0
while True:
    if current < 4000000:
        if current % 2 == 0:  # If current is even, add on to sum
            final_sum += current
        # Increment to the next number in the Fibonacci sequence by adding together the previous and current number
        temp = prev
        prev = current
        current = current + temp

    else:
        break
print(final_sum)
